/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mdc.login_form;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author bryan
 */
public class Registration_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    
    String image_path = null;
    
    public Registration_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border header_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        header.setBorder(header_border);
        
        Border minimize_border = BorderFactory.createMatteBorder(1,1,1,0,Color.BLACK);
        minimize.setBorder(minimize_border);
        
        Border close_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        close.setBorder(close_border);
        
        Border glob_panel_border = BorderFactory.createMatteBorder(1,1,1,1,Color.ORANGE);
        jPanel1.setBorder(glob_panel_border);
        
        Border sign_in_label_border = BorderFactory.createMatteBorder(0,0,1,0, Color.LIGHT_GRAY);
        sign_in_label.setBorder(sign_in_label_border);
        
        Border input_border = BorderFactory.createMatteBorder(1,5,1,1,Color.WHITE);
        full_name_input.setBorder(input_border);
        username_input.setBorder(input_border);
        password_input.setBorder(input_border);
        confirm_password_input.setBorder(input_border);
        phone_input.setBorder(input_border);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(male_radio_button);
        bg.add(female_radio_button);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        full_name_label = new javax.swing.JLabel();
        full_name_input = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        confirm_password_label = new javax.swing.JLabel();
        confirm_password_input = new javax.swing.JPasswordField();
        phone_label = new javax.swing.JLabel();
        phone_input = new javax.swing.JTextField();
        phone_label1 = new javax.swing.JLabel();
        male_radio_button = new javax.swing.JRadioButton();
        female_radio_button = new javax.swing.JRadioButton();
        profile_image_label = new javax.swing.JLabel();
        profile_image_button = new javax.swing.JButton();
        profile_image_path = new javax.swing.JLabel();
        sign_in_label = new javax.swing.JLabel();
        minimize = new javax.swing.JPanel();
        minimize_text = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        close_text = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        header_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        register_button.setBackground(new java.awt.Color(235, 47, 6));
        register_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        register_button.setForeground(new java.awt.Color(255, 255, 255));
        register_button.setText("Register");
        register_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_buttonMouseExited(evt);
            }
        });
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        full_name_label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        full_name_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        full_name_label.setText("Full Name:");

        username_label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        username_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username_label.setText("Username:");

        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });

        password_label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        password_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        password_label.setText("Password:");

        confirm_password_label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        confirm_password_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        confirm_password_label.setText("Confirm Password:");

        phone_label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        phone_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        phone_label.setText("Phone:");

        phone_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_inputActionPerformed(evt);
            }
        });
        phone_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_inputKeyTyped(evt);
            }
        });

        phone_label1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        phone_label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        phone_label1.setText("Gender:");

        male_radio_button.setSelected(true);
        male_radio_button.setText("Male");
        male_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radio_buttonActionPerformed(evt);
            }
        });

        female_radio_button.setText("Female");
        female_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radio_buttonActionPerformed(evt);
            }
        });

        profile_image_label.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        profile_image_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profile_image_label.setText("Profile Image:");

        profile_image_button.setText("select image");
        profile_image_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_image_buttonActionPerformed(evt);
            }
        });

        profile_image_path.setText("image path");

        sign_in_label.setText(">> Already have an Account? Click here to Sign in!");
        sign_in_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_in_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_in_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_in_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_in_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(male_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(female_radio_button))
                            .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(profile_image_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(profile_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(register_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(full_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(28, 28, 28)
                            .addComponent(full_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirm_password_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(username_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phone_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(profile_image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(username_input)
                                .addComponent(password_input)
                                .addComponent(confirm_password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(sign_in_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(full_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(full_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label)
                    .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_password_label)
                    .addComponent(confirm_password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_label)
                    .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_label1)
                    .addComponent(male_radio_button)
                    .addComponent(female_radio_button))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_image_label)
                    .addComponent(profile_image_button)
                    .addComponent(profile_image_path))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sign_in_label)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        minimize_text.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        minimize_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize_text.setText("-");

        javax.swing.GroupLayout minimizeLayout = new javax.swing.GroupLayout(minimize);
        minimize.setLayout(minimizeLayout);
        minimizeLayout.setHorizontalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(minimize_text, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        minimizeLayout.setVerticalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        close_text.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        close_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_text.setText("X");

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close_text, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        header.setBackground(new java.awt.Color(0, 84, 140));

        header_text.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        header_text.setForeground(new java.awt.Color(255, 255, 255));
        header_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_text.setText("REGISTER");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_text, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header_text, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        Border minimize_border = BorderFactory.createMatteBorder(1,1,1,0,Color.WHITE);
        minimize.setBorder(minimize_border);
        minimize_text.setForeground(Color.WHITE);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        Border minimize_border = BorderFactory.createMatteBorder(1,1,1,0,Color.BLACK);
        minimize.setBorder(minimize_border);
        minimize_text.setForeground(Color.BLACK);
    }//GEN-LAST:event_minimizeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        Border minimize_border = BorderFactory.createMatteBorder(1,1,1,1,Color.WHITE);
        close.setBorder(minimize_border);
        close_text.setForeground(Color.WHITE);    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        Border minimize_border = BorderFactory.createMatteBorder(1,1,1,1,Color.BLACK);
        close.setBorder(minimize_border);
        close_text.setForeground(Color.BLACK);    }//GEN-LAST:event_closeMouseExited

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        String fname = full_name_input.getText();
        String username = username_input.getText();
        String pass = String.valueOf(password_input.getPassword());
        String confirm_pass = String.valueOf(confirm_password_input.getPassword());
        String phone = phone_input.getText();
        String gender = "Male";
        
        if(female_radio_button.isSelected()){
            gender = "Female";
        }
        
        if(verifyFields()){
            if(!checkUsername(username)){
                PreparedStatement ps;
                ResultSet rs;
                
                String registerUserQuery = "INSERT into `users`(`full_name`, `username`, `password`, `phone`, `gender`, `picture`) VALUES (?,?,?,?,?,?)";
                
                try {
                    ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, fname);
                    ps.setString(2, username);
                    ps.setString(3, pass);
                    ps.setString(4, phone);
                    ps.setString(5, gender);
                    
                    try {
                        // save the image as blob
                        if(image_path != null){
                            InputStream image = new FileInputStream(new File(image_path));
                            ps.setBlob(6, image);
                        } else {
                            ps.setNull(6, java.sql.Types.NULL);
                        }
                        
                        if(ps.executeUpdate() != 0){
                            JOptionPane.showMessageDialog(null, "Your Account has been created!");
                        } else {
                            JOptionPane.showMessageDialog(null, "Error: Check your information!");
                        }
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
        
    }//GEN-LAST:event_register_buttonActionPerformed

    private void register_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseEntered
        register_button.setBackground(new Color(225,20,2));
    }//GEN-LAST:event_register_buttonMouseEntered

    private void register_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_buttonMouseExited
        register_button.setBackground(new Color(235,47,6));
    }//GEN-LAST:event_register_buttonMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void phone_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_inputActionPerformed

    private void male_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radio_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_radio_buttonActionPerformed

    private void female_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radio_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_radio_buttonActionPerformed

    private void profile_image_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_image_buttonActionPerformed
        String path = null;
        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter extension = new FileNameExtensionFilter("*Images",".jpg",".png",".jpeg");
        chooser.addChoosableFileFilter(extension);
        
        int file_state = chooser.showSaveDialog(null);
        
        if(file_state == JFileChooser.APPROVE_OPTION){
            File selectedImage = chooser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            profile_image_path.setText(path);
            
            image_path = path;
        }
    }//GEN-LAST:event_profile_image_buttonActionPerformed

    private void phone_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_inputKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_phone_inputKeyTyped

    private void sign_in_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_labelMouseClicked
        Login_Form lf = new Login_Form();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_sign_in_labelMouseClicked

    private void sign_in_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_labelMouseEntered
        Border create_account_border = BorderFactory.createMatteBorder(0,0,1,0,Color.RED);
        sign_in_label.setBorder(create_account_border);
    }//GEN-LAST:event_sign_in_labelMouseEntered

    private void sign_in_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_in_labelMouseExited
        Border label_create_account_border = BorderFactory.createMatteBorder(0,0,1,0, Color.LIGHT_GRAY);
        sign_in_label.setBorder(label_create_account_border);
    }//GEN-LAST:event_sign_in_labelMouseExited

    public boolean verifyFields(){
        String fname = full_name_input.getText();
        String uname = username_input.getText();
        String phone = phone_input.getText();
        String pass = String.valueOf(password_input.getPassword());
        String confirm_pass = String.valueOf(confirm_password_input.getPassword());
        
        if(fname.trim().equals("") || uname.trim().equals("") || phone.trim().equals("") || pass.trim().equals("") || confirm_pass.trim().equals("")){
            JOptionPane.showMessageDialog(null, "One or more fields are empty!");
            return false;
        } else if(!pass.equals(confirm_pass)){
            JOptionPane.showMessageDialog(null, "Passwords don't match!", "Confirm Password", 2);
            return false;
        } else {
            return true;
        }
    }
    
    public boolean checkUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        
        boolean username_exists = false;
        
        String query = "SELECT * FROM `users` WHERE `username` = ?";
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if(rs.next()){
                username_exists = true;
                JOptionPane.showMessageDialog(null, "This username is already taken. Choose another one", "Username Failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registration_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exists;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel close;
    private javax.swing.JLabel close_text;
    private javax.swing.JPasswordField confirm_password_input;
    private javax.swing.JLabel confirm_password_label;
    private javax.swing.JRadioButton female_radio_button;
    private javax.swing.JTextField full_name_input;
    private javax.swing.JLabel full_name_label;
    private javax.swing.JPanel header;
    private javax.swing.JLabel header_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male_radio_button;
    private javax.swing.JPanel minimize;
    private javax.swing.JLabel minimize_text;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField phone_input;
    private javax.swing.JLabel phone_label;
    private javax.swing.JLabel phone_label1;
    private javax.swing.JButton profile_image_button;
    private javax.swing.JLabel profile_image_label;
    private javax.swing.JLabel profile_image_path;
    private javax.swing.JButton register_button;
    private javax.swing.JLabel sign_in_label;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
